### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGKILL' [ on Windows]

### ISSUE THREAD

**Issue by buendiya** [celery/billiard#135]
I am using celery on Windows. And I set CELERYD_TASK_TIME_LIMIT to 1200. Depends on the document,  'The worker processing the task will be killed and replaced with a new one when this is exceeded.'

But when the executing time of my task exceeds the CELERYD_TASK_TIME_LIMIT setting, I got the following error:

> [2015-01-04 12:56:27,994: ERROR/MainProcess] Thread 'TimeoutHandler' crashed: AttributeError("'module' object has no attribute 'SIGKILL'",)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\billiard\pool.py", line 472, in run
    return self.body()
  File "C:\Python27\lib\site-packages\billiard\pool.py", line 708, in body
    for _ in self.handle_timeouts():
  File "C:\Python27\lib\site-packages\billiard\pool.py", line 699, in handle_timeouts
    on_hard_timeout(job)
  File "C:\Python27\lib\site-packages\billiard\pool.py", line 653, in on_hard_timeout
    self._trywaitkill(process)
  File "C:\Python27\lib\site-packages\billiard\pool.py", line 666, in _trywaitkill
    _kill(worker.pid, signal.SIGKILL)
AttributeError: 'module' object has no attribute 'SIGKILL'

**Comment by ask** [comment]
Fix will be out shortly (3.3.0.20)
