### ISSUE TITLE
"No such file or directory" error after upgrading Ubuntu

### ISSUE THREAD

**Issue by fern4lvarez** [celery/billiard#139]
We start celery workers inside Ubuntu 12.04 containers. Few days ago we decided to `dist-upgrade` the image the containers are based on, and when starting the celery worker, we found that billiard raised an `OSError` when Celery was starting-up.

We are using 

~~~
celery==3.1.17
kombu==3.0.24
billiard==3.3.0.19
~~~

(among others) for this project.

Does anyone have a quick idea on why this happened? Here is the error trace, where you can also find more information about the celery worker. 

~~~
/app/.paasprovider/python/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

 -------------- celery@depzrgh893w-16193 v3.1.17 (Cipater)
---- **** -----
--- * ***  * -- Linux-3.13.0-32-generic-x86_64-with-debian-wheezy-sid
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7fc3a778a4d0
- ** ---------- .> transport:   sqla+mysql://root:...@....:3306/tasks
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> maintenance      exchange=maintenance(direct) key=maintenance
                .> tasks            exchange=tasks(direct) key=tasks

[tasks]
  . app.tasks.add
  . app.tasks.add_api_creds
  . app.tasks.add_db_certificate
  . app.tasks.backup_and_remove
  . app.tasks.check_worker_life
  . app.tasks.cleanup_kombu_message_table
  . app.tasks.cleanup_old_db_dumps
  . app.tasks.provision_db_instance
  . app.tasks.remove
  . app.tasks.update
[2015-04-10 14:01:07,414: ERROR/MainProcess] Unrecoverable error: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/app/.paasprovider/python/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 117, in on_start
    **self.options)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/billiard/pool.py", line 925, in __init__
    self._setup_queues()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/billiard/pool.py", line 1268, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/billiard/queues.py", line 370, in __init__
    self._rlock = Lock()
  File "/app/.paasprovider/python/lib/python2.7/site-packages/billiard/synchronize.py", line 160, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/app/.paasprovider/python/lib/python2.7/site-packages/billiard/synchronize.py", line 70, in __init__
    kind, value, maxvalue, self._make_name(), unlink_immediately)
OSError: [Errno 2] No such file or directory
~~~

**Comment by fern4lvarez** [comment]
Closed as it was an issue on our end
