### ISSUE TITLE
AttributeError when trying to access `__spec__`

### ISSUE THREAD

**Issue by jakirkham** [celery/billiard#145]
Maybe `__spec__` should be retrieved through `getattr` as well with a `None` returned on failure? If the real goal is to get the module's actual name, it might be better to use `__file__` and parse out the filename using `os.path.basename` and `os.path.splitext`. Just a thought.

    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/process.py", line 124, in start
        self._popen = self._Popen(self)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/context.py", line 339, in _Popen
        return Popen(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_spawn_posix.py", line 38, in __init__
        super(Popen, self).__init__(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_fork.py", line 22, in __init__
        self._launch(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_spawn_posix.py", line 50, in _launch
        prep_data = spawn.get_preparation_data(process_obj._name)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/spawn.py", line 262, in get_preparation_data
        main_mod_name = getattr(main_module.__spec__, "name", None)
    AttributeError: 'module' object has no attribute '__spec__'

**Comment by ask** [comment]
Thanks! Fixed in master

**Comment by jakirkham** [comment]
Great!

**Comment by ajay-manwani** [comment]
Thank you !
