### ISSUE TITLE
`BytesIO` object must use `getvalue`

### ISSUE THREAD

**Issue by jakirkham** [celery/billiard#151]
Switch to using `getvalue` for `BytesIO` object as there is no `getbuffer`.

    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/process.py", line 124, in start
        self._popen = self._Popen(self)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/context.py", line 339, in _Popen
        return Popen(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_spawn_posix.py", line 38, in __init__
        super(Popen, self).__init__(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_fork.py", line 22, in __init__
        self._launch(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_spawn_posix.py", line 70, in _launch
        os.write(parent_w, fp.getbuffer())
    AttributeError: '_io.BytesIO' object has no attribute 'getbuffer'

**Comment by ask** [comment]
Thanks, Fixed in master!
