### ISSUE TITLE
Hangs when trying to call `os.close`

### ISSUE THREAD

**Issue by jakirkham** [celery/billiard#153]
Thinking there is a solution worth borrowing from here ( http://www.tutorialspoint.com/python/os_pipe.htm ).

    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/xopt_ilastik/local/src/nanshe-git/tests/test_nanshe/test_box/test_spams_sandbox.py", line 166, in test_call_multiprocessing_queue_spams_trainDL_1
        "mode" : 2
      File "/xopt_ilastik/local/src/nanshe-git/nanshe/box/spams_sandbox.py", line 100, in call_multiprocessing_queue_spams_trainDL
        out_queue = mp.Queue()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/context.py", line 138, in Queue
        return Queue(maxsize, ctx=self.get_context())
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/queues.py", line 45, in __init__
        self._rlock = ctx.Lock()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/context.py", line 103, in Lock
        return Lock(ctx=self.get_context())
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/synchronize.py", line 182, in __init__
        SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/synchronize.py", line 101, in __init__
        register(self._semlock.name)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/semaphore_tracker.py", line 71, in register
        self._send('REGISTER', name)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/semaphore_tracker.py", line 78, in _send
        self.ensure_running()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/semaphore_tracker.py", line 62, in ensure_running
        os.close(w)
    OSError: [Errno 9] Bad file descriptor

**Comment by ask** [comment]
Are you on Windows or are you using FORCE_EXECV/forking_enable?

**Comment by jakirkham** [comment]
This is on Mac, actually.

**Comment by ask** [comment]
Ok, pretty sure I have only tested fork so far, so that probably requires some work

**Comment by jakirkham** [comment]
Alright, let me know if I can help, I am very interested in getting this to work.

**Comment by thedrow** [comment]
@jakirkham Feel free to contribute a PR.

**Comment by jakirkham** [comment]
Unfortunately I don't know the cause. So I don't know how to fix it either.

**Comment by thedrow** [comment]
We need a test case at the very least to debug this. I'm not sure you'll be able to provide one since so much time has passed. Sorry about that,

If you can, please do.
