### ISSUE TITLE
Crashes with broken pipe

### ISSUE THREAD

**Issue by spulec** [celery/billiard#16]
This makes our workers crash/hang every hour or so.

```
Traceback (most recent call last):
File "../lib/python2.7/site-packages/billiard/process.py", line 273, in _bootstrap
self.run()
File "../lib/python2.7/site-packages/billiard/process.py", line 122, in run
self._target(*self._args, **self._kwargs)
File "../lib/python2.7/site-packages/billiard/pool.py", line 302, in worker
put((ACK, (job, i, time.time(), pid)))
File "../lib/python2.7/site-packages/billiard/queues.py", line 377, in put
return send(obj)
IOError: [Errno 32] Broken pipe
```

celery==3.0.7
django-celery==3.0.4
kombu==2.4.3
billiard==2.7.3.12

We're using the SQS backend.

**Comment by mengmengpengpeng** [comment]
I met the same problem.
Traceback (most recent call last):
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/pool.py", line 374, in workloop
    put((READY, (job, i, (False, einfo), inqW_fd)))
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/queues.py", line 403, in send_payload
    self._writer.send_bytes(value)
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/connection.py", line 227, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/connection.py", line 453, in _send_bytes
    self._send(header + buf)
  File "/home/work/software/python_package/lib/python2.7/site-packages/billiard/connection.py", line 406, in _send
    n = write(self._handle, buf)
OSError: [Errno 32] Broken pipe

I got this.It confused me for one week..
