### ISSUE TITLE
AttributeError: 'LaxBoundedSemaphore' object has no attribute '_Semaphore__value'

### ISSUE THREAD

**Issue by dessant** [celery/billiard#172]
I'm starting the worker with `--autoscale=10,1`, when using `--concurrency=10` instead, the worker does not crash.

```
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:3.4.3
            billiard:3.3.0.20 py-amqp:1.4.6
```
```python
[2015-09-25 00:56:02,882: INFO/MainProcess] Scaling up 1 processes.
[2015-09-25 00:56:02,882: WARNING/MainProcess] 'Autoscaler' crashed: AttributeError("'LaxBoundedSemaphore' object has no attribute '_Semaphore__value'",)
[2015-09-25 00:56:02,882: WARNING/MainProcess] Traceback (most recent call last):
[2015-09-25 00:56:02,882: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\utils\threads.py", line 64, in run
    body()
[2015-09-25 00:56:02,897: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\worker\autoscale.py", line 81, in body
    self.maybe_scale()
[2015-09-25 00:56:02,897: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\worker\autoscale.py", line 95, in maybe_scale
    if self._maybe_scale(req):
[2015-09-25 00:56:02,913: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\worker\autoscale.py", line 88, in _maybe_scale
    self.scale_up(cur - procs)
[2015-09-25 00:56:02,913: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\worker\autoscale.py", line 127, in scale_up
    return self._grow(n)
[2015-09-25 00:56:02,929: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\worker\autoscale.py", line 137, in _grow
    self.pool.grow(n)
[2015-09-25 00:56:02,929: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\pool.py", line 1206, in grow
    self._putlock.grow()
[2015-09-25 00:56:02,944: WARNING/MainProcess] File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\pool.py", line 172, in grow
    self._Semaphore__value += 1
[2015-09-25 00:56:02,960: WARNING/MainProcess] AttributeError: 'LaxBoundedSemaphore' object has no attribute '_Semaphore__value'
```

**Comment by dessant** [comment]
@ask, will this be merged back into master?

**Comment by ask** [comment]
Thanks for reminding me, it's now been ported into master.

**Comment by dessant** [comment]
np, thanks a lot :stuck_out_tongue:
