### ISSUE TITLE
ImportError: No module named 'billiard.py3.compat

### ISSUE THREAD

**Issue by dessant** [celery/billiard#178]
After upgading from billiard 3.3.0.20 to 3.3.0.21:

```python
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    start_celery()
  File "run.py", line 29, in start_celery
    worker.start_worker()
  File "e:\dev\prs\main\app\worker.py", line 45, in start_worker
    app.worker_main(argv)
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\app\base.py", line 206, in worker_main
    app=self).execute_from_commandline(argv)
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\bin\base.py", line 304, in execute_from_commandline
    self.maybe_patch_concurrency(argv)
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\bin\base.py", line 321, in maybe_patch_concurrency
    maybe_patch_concurrency(argv, *pool_option)
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\__init__.py", line 128, in maybe_patch_concurrency
    concurrency.get_implementation(pool)
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\concurrency\__init__.py", line 29, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "e:\dev\envs\py34_x86\Python\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\celery\concurrency\prefork.py", line 14, in <module>
    from billiard.pool import RUN, CLOSE, Pool as BlockingPool
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\pool.py", line 34, in <module>
    from .dummy import DummyProcess
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\dummy\__init__.py", line 50, in <module>
    from billiard.connection import Pipe
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\connection.py", line 8, in <module>
    from .py3 import connection
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\py3\connection.py", line 26, in <module>
    from ..reduction import ForkingPickler
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\reduction.py", line 6, in <module>
    from .py3 import reduction
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\billiard\py3\reduction.py", line 69, in <module>
    from .compat import _winapi
ImportError: No module named 'billiard.py3.compat'
```

**Comment by ask** [comment]
Seems this is not a bug in 3.3.0.21, but from a temporary change that got into the Windows wheel specifically.

Please upgrade to billiard 3.3.0.22, I just released this version and it should not have this problem:

   pip install -U billiard

**Comment by dessant** [comment]
.22 works nicely, thanks a lot
