### ISSUE TITLE
TypeError after upgrading to v3.5.0

### ISSUE THREAD

**Issue by michael-k** [celery/billiard#188]
I get the following `TypeError` after upgrading to billiard v3.5.0:

```python
[ERROR/MainProcess] Unrecoverable error: TypeError('_Popen() takes 1 positional argument but 2 were given',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/site-packages/billiard/process.py", line 122, in start
    self._popen = self._Popen(self)
TypeError: _Popen() takes 1 positional argument but 2 were given
```

We are running Django 1.9.9 with celery 3.1.23.  The `TypeError` only occurs, when starting celery with the `celery worker -B` (`-B`: celery beat periodic task scheduler).  It works fine when starting a seperate worker and beat server: `celery worker` and `celery beat`.

**Comment by auvipy** [comment]
can you try this with celery master ??

**Comment by michael-k** [comment]
I updated the requirements.txt with these lines:
```
git+https://github.com/celery/celery.git@7eb2214f84bf6dc25c374597c6f9c59987bf9e22#egg=celery
git+https://github.com/celery/django-celery.git@e64c02967260085d4a1ff235239e3c5553dfaded#egg=django-celery
```

Now this happens:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 9, in <module>
    load_entry_point('celery==4.0.0rc3', 'console_scripts', 'celery')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/celery/__init__.py", line 146, in <module>
    from celery import five  # noqa
  File "/usr/local/lib/python3.5/site-packages/celery/five.py", line 12, in <module>
    from vine import five
ImportError: No module named 'vine'
```

**Comment by michael-k** [comment]
Another try:
```
celery==4.0.0rc3
git+https://github.com/celery/django-celery.git@e64c02967260085d4a1ff235239e3c5553dfaded#egg=django-celery
```

Result:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 13, in main
    from celery.bin.celery import main
  File "/usr/local/lib/python3.5/site-packages/celery/bin/__init__.py", line 3, in <module>
    from .base import Option
  File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 18, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
  File "/usr/local/lib/python3.5/site-packages/celery/five.py", line 156, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.5/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/usr/local/lib/python3.5/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.5/site-packages/celery/utils/__init__.py", line 16, in <module>
    from .functional import memoize  # noqa
  File "/usr/local/lib/python3.5/site-packages/celery/utils/functional.py", line 17, in <module>
    from kombu.utils.functional import (
ImportError: cannot import name 'LRUCache'
```

**Comment by michael-k** [comment]
Next try:
```
celery==4.0.0rc3
git+https://github.com/celery/django-celery.git@e64c02967260085d4a1ff235239e3c5553dfaded#egg=django-celery
kombu==v4.0.0rc3
```

Result: it works in term of starting, but runs into errors when executing tasks:
```
[2016-08-15 12:53:17,175: WARNING/MainProcess] celery@<projectname>.8f1b1013d25e ready.

[2016-08-15 12:53:17,176: CRITICAL/MainProcess] Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type json (application/json)',) [type:'application/json' encoding:'utf-8' headers:{}]

body: '{"taskset": null, "timelimit": [null, null], "id": "004e4854-7bfc-49bc-9191-a0ac33fa2e99", "retries": 0, "task": "<projectname>.<taskname>", "utc": true, "args": [], "chord": null, "group": null, "kwargs": {}, "eta": null, "expires": "2016-08-15T12:58:16.242653+02:00", "callbacks": null, "errbacks": null}' (307b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 535, in on_task_received
     type_ = message.headers['task']                # protocol v2
KeyError: 'task'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 540, in on_task_received
    payload = message.decode()
  File "/usr/local/lib/python3.5/site-packages/kombu/message.py", line 155, in decode
    self._decoded_cache = self._decode()
  File "/usr/local/lib/python3.5/site-packages/kombu/message.py", line 160, in _decode
    self.content_encoding, accept=self.accept)
  File "/usr/local/lib/python3.5/site-packages/kombu/serialization.py", line 176, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type json (application/json)
```

**Comment by xeor** [comment]
This works fine if I downgrade to `billiard==3.3.0.20` as https://github.com/celery/celery/issues/2530 mention.. I think this problem happens now if you don't specify the versions when using pip. Ie, this problem will start happening to many people soon.... :(

**Comment by istinspring** [comment]
Same there. Downgrading as @xeor resolved this issue.

**Comment by michael-k** [comment]
Downgrading does not resolve this issue, it just avoids it.

**Comment by ask** [comment]
Billiard 3.5 is to be used with Celery 4 only, this is why Celery 3.1 requires billiard < 3.5

**Comment by ask** [comment]
Ah, yeah, I guess that's the downside of being decoupled from Celery.

There's seems to be a bug in some pip version which forces it to ignore the dependencies mandated.

**Comment by hotea** [comment]
I solved this by
change
`from billiard.process import Process`
to
`from billiard.context import Process`
