### ISSUE TITLE
UnboundLocalError: local variable 'chunk' referenced before assignment

### ISSUE THREAD

**Issue by diresi** [celery/billiard#191]
Hi,

I'm trying to implement a signal handler for SIGUSR2 and have applied the monkey patch from celery/celery#2615 ([this comment](https://github.com/celery/celery/issues/2615#issuecomment-207085293)).

While SIGUSR2 is available for my purpuse using this patch, the `_recv()` implementation [here](https://github.com/celery/billiard/blob/master/billiard/connection.py#L427) actually doesn't handle EINTR.

Shouldn't the exception handler `continue` upon `EINTR`s?

This happens using celery 3.1.23 with billiard 3.5.0.0.
The full exception stack is:
```
Traceback (most recent call last):
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 295, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 355, in workloop
    req = wait_for_job()
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 457, in receive
    ready, req = _receive(1.0)
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 429, in _recv
    return True, loads(get_payload())
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/queues.py", line 355, in get_payload
    return self._reader.recv_bytes()
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/connection.py", line 245, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/connection.py", line 457, in _recv_bytes
    buf = self._recv(4)
  File "/home/ente/venv/local/lib/python2.7/site-packages/billiard/connection.py", line 428, in _recv
    n = len(chunk)
UnboundLocalError: local variable 'chunk' referenced before assignment
```

**Comment by ask** [comment]
Ah, that would make sense since we ported this from Python 3.4 and EINTR is handled automatically there now.
