### ISSUE TITLE
Pool crashes under Windows

### ISSUE THREAD

**Issue by SPKorhonen** [celery/billiard#226]
When creating Pool under Windows AttributeError is raised. This prevents the usage of billiard and by extension Celery 4.0 under Windows. For further discussion see https://github.com/celery/celery/issues/3821 For a fix see #225

For minimal example, please see below:

import billiard
p=billiard.Pool()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\billiard\context.py", line 165, in Pool
    context=self.get_context())
  File "C:\Program Files\Python36\lib\site-packages\billiard\pool.py", line 1008, in __init__
    self._create_worker_process(i)
  File "C:\Program Files\Python36\lib\site-packages\billiard\pool.py", line 1117, in _create_worker_process
    w.start()
  File "C:\Program Files\Python36\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python36\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python36\lib\site-packages\billiard\popen_spawn_win32.py", line 79, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python36\lib\site-packages\billiard\reduction.py", line 99, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Pool.__init__.<locals>.Process'

**Comment by auvipy** [comment]
clozing as fixed
