### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 4 (SIGILL).

### ISSUE THREAD

**Issue by aakaruimahesh** [celery/billiard#227]
[2017-06-16 13:18:14,866: ERROR/MainProcess] Process 'PoolWorker-6' pid:6223 exited with 'signal 4 (SIGILL)'
[2017-06-16 13:18:14,877: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 4 (SIGILL).',)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1224, in mark_as_worker_lost
human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 4 (SIGILL).
[2017-06-16 13:18:19,010: INFO/MainProcess] Received task: rare.tasks.process_audio_chunk[3ed1c835-8755-4145-8999-10ad88d8cc10]
[2017-06-16 13:18:19,905: ERROR/MainProcess] Process 'PoolWorker-1' pid:6218 exited with 'signal 4 (SIGILL)'
[2017-06-16 13:18:19,916: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 4 (SIGILL).',)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1224, in mark_as_worker_lost
human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 4 (SIGILL).

**Comment by kcdipesh** [comment]
I'm also getting this issue?  Has anyone else got this issue or know anything more. If so please let me know. Thanks

**Comment by listingmirror** [comment]
I see these a fair bit, maybe one per 2 hours. Not totally sure why..

**Comment by saorio** [comment]
You would try Ofair option. I worked it.

**Comment by auvipy** [comment]
could you verify this again against recent release?

**Comment by peketamin** [comment]
Check this comment please: https://github.com/celery/celery/issues/3085#issuecomment-317012574.
