### ISSUE TITLE
Internal error: AssertionError() assert self._parent is current_process()

### ISSUE THREAD

**Issue by buckensl** [celery/billiard#237]
We are using 
billiard==3.3.0.20
celery==3.1.18

```
2017-03-26 00:36:09.476 +0000 CRITICAL [__init__._process_task] Internal error: AssertionError()
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 227, in _process_task
    req.execute_using_pool(self.pool)
  File "venv/lib/python2.7/site-packages/celery/worker/job.py", line 263, in execute_using_pool
    correlation_id=uuid,
  File "venv/lib/python2.7/site-packages/celery/concurrency/base.py", line 156, in apply_async
    **options)
  File "venv/lib/python2.7/site-packages/billiard/pool.py", line 1431, in apply_async
    self._start_timeout_handler()
  File "venv/lib/python2.7/site-packages/billiard/pool.py", line 1288, in _start_timeout_handler
    self._timeout_handler.start()
  File "venv/lib/python2.7/site-packages/billiard/pool.py", line 487, in start
    super(PoolThread, self).start(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/billiard/dummy/__init__.py", line 69, in start
    assert self._parent is current_process()
AssertionError
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 227, in _process_task
    req.execute_using_pool(self.pool)
  File "venv/lib/python2.7/site-packages/celery/worker/job.py", line 263, in execute_using_pool
    correlation_id=uuid,
  File "venv/lib/python2.7/site-packages/celery/concurrency/base.py", line 156, in apply_async
    **options)
  File "venv/lib/python2.7/site-packages/billiard/pool.py", line 1431, in apply_async
    self._start_timeout_handler()
  File "venv/lib/python2.7/site-packages/billiard/pool.py", line 1288, in _start_timeout_handler
    self._timeout_handler.start()
  File "venv/lib/python2.7/site-packages/billiard/pool.py", line 487, in start
    super(PoolThread, self).start(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/billiard/dummy/__init__.py", line 69, in start
    assert self._parent is current_process()
AssertionError
```

**Comment by auvipy** [comment]
plz use newer versions

**Comment by buckensl** [comment]
@auvipy can you point me to the version that has a fix for this issue?

**Comment by auvipy** [comment]
Not specific, but you should use latest release of celery 4.1 is current and 4.2 is going to be release by this month hopefully. After using the latest releases if you still get the error feel free to report here again
