### ISSUE TITLE
WorkerLostError: Worker exited prematurely: exitcode 0 when shutting down worker

### ISSUE THREAD

**Issue by tabascoterrier** [celery/billiard#273]
I'm new to Celery, so do correct me if I'm missing the obvious!

When Ctrl+Cing (or sending SIGTERM) to the Celery process, Im getting WorkerLostErrors a lot of (but not all) the time:
```
[2016-11-29 16:18:07,837: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0.',)
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/async/hub.py", line 289, in create_loop
    events = poll(poll_timeout)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/utils/eventio.py", line 84, in poll
    return self._epoll.poll(timeout if timeout is not None else -1)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/apps/worker.py", line 282, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/billiard/pool.py", line 1224, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0.
```

I'm seeing this on both macOS 10.12.1 and Ubuntu 16.04 

To reproduce:
Load the queue:
python task_test.py

Run the worker:
celery worker -A task_test --loglevel=INFO --concurrency=10

Give it a few seconds for some tasks to run and complete, and Ctrl+C the worker.

Expected behaviour: Tasks exit cleanly

Observed behaviour: WorkerLostErrors

Minimal test case task_test.py:
```python
import time
import random
from celery import Celery

app = Celery('tasks', broker='redis://127.0.0.1')

@app.task(name='test_task')
def test_task(wait_for):
    time.sleep(wait_for)

if __name__ == '__main__':
    for x in range(1000):
        test_task.delay(random.randrange(1, 10))
```

celery -A task_test report
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: 'redis://127.0.0.1:6379//'
```

I'm seeing this on both macOS 10.12.1 and Ubuntu 16.04

**Comment by thedrow** [comment]
The OP said it happens on Ubuntu and MacOS as well so nevermind...

**Comment by BillSchumacher** [comment]
I have the same issue; perhaps it's because in my tasks I'm retrying on timeout or scheduling more as the worker is shutting down? I lose "some" but not all workers, my workers are usually maxed out running 16 tasks continuously, I might lose 2 or 4 per group of 16.

**Comment by auvipy** [comment]
could anyone check this PR https://github.com/celery/billiard/pull/279

**Comment by wakemaster39** [comment]
installed billard master and at least in my case this did not resolve the problem.

This issue is not occurring for me when trying to exit or restart workers. This error is occurring when I raise specific exceptions, as noted above with BaseException. 

I am trying to use some of the latest attrs features of auto_exc=True to create custom exceptions. 

```python
@attrs(auto_exc=True, auto_attribs=True)
class PostProcessorException(Exception):
    message: str
```

Raising this exception from a script or debugging celery with forking disabled, everything works fine and as expected. The errors only occur when this exception is raised in a fork, where the master logs the worker lost error.

Raising this error immediately kills the job. There is 0 output once this error is raised. I have the celery log level set to debug, I have as much logging as I can wrap around things and the job just dies once this exception raises.

**Comment by cocobuster** [comment]
I was able to reproduce this issue, by  stopping supervisor while long task was executing. The main issue was that the task was being removed from RabbitMq queue and lost for ever, so this is a big issue!

Reproduction steps:

# create a long task /tasks/test_celery.py
@shared_task
def send_long_tasks(id=0):
    logger.info("CELERY_TEST: Starting Buggy task id={} !".format(id))
    # Task will run for 5 minutes
    time.sleep(300)
    logger.info("CELERY_TEST: Ending Buggy task id={} !".format(id))


# Django celery settings.py
CELERY_RESULT_BACKEND = 'django-db'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_RESULT_EXPIRES = timedelta(7)
CELERY_TASK_ACKS_LATE=True
CELERY_RESULT_PERSISTENT=True
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_BROKER_POOL_LIMIT = None
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TASK_QUEUES = ( Queue('test_celery', Exchange('test_celery'), routing_key='test_celery'),)

CELERY_TASK_ROUTES = {
    'my_project.test_tasks.*': {
        'queue': 'test_celery', 'routing_key': 'test_celery',
    },
}



# Supervisor test_celery.conf
[program:test_worker]
command=/home/tool/venv/bin/celery worker -A my_project --loglevel=INFO -Q my_project --concurrency=4 test-worker@%%h -O fair
directory=/home/tool/www/my_project
stdout_logfile=/var/log/celery/worker.log
stderr_logfile=/var/log/celery/worker.log
autostart=true
autorestart=true
startsecs=10

stopwaitsecs = 60
stopasgroup=true



# Every time I was sending a long task and trying to stop it in the middle of its execution using supervisor.
python>send_long_tasks.delay(id=1022)

# Then to get this error, ALL I had to do was to stop supervisor!
Terminal>sudo supervisor stop test_task

# Checking my var/log/celery/worker.log, I had the following error
...
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/billiard/pool.py", line 1224, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0.
...

OS: Ubuntu 18.04
       Celery: 4.3.0


# Solution
The goal was to tell the worker to stop taking new task, by first finishing the task it was currently running, if it took too long (more then 60 sec as specified in supervisor configuration file stopwaitsecs=60) we would terminate the worker and re-queue it.. we didnt want to drop the task and lose it!

The solution was in the supervisor configuration file... somehow "stopasgroup=true" was the problem. The way it terminal workers process and subprocess is too agressive and doesnt allow sobprocess to re-queue task. 

Instead I REMOVED  "stopasgroup=true" and replaced it with "killasgroup=true", and it did the trick!

Tasks were finally being requeue, and not lost, the error "WorkerLostError" went away, and all workers sub-process closed with "supervisorctl stop all" call.

This was a tricky bug to fix, I hope this can help you!
Cheers,
Cocobuster

**Comment by mikey555** [comment]
for anyone running celery on heroku, keep in mind that when heroku cycles your dyno, celery will be shut down. I have celery 4.3.0 running on a heroku worker dyno, and I receive this error.

**Comment by auvipy** [comment]
try celery 4.4.2+ and report again

**Comment by mikey555** [comment]
> try celery 4.4.2+ and report again

I originally had 4.4.2 and was getting this error, so I downgraded to 4.3.0 because I read it was more stable with regards to this error.

**Comment by obravo7** [comment]
Any updates on this? I tried switching from celery version 4.4.2 to 4.3.0 but still getting the same error. See traceback error below

```
celery_1  | Traceback (most recent call last):
celery_1  |   File "/root/anaconda3/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
celery_1  |     human_status(exitcode)),
celery_1  | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

My celery task runs on GPU using tensorflow, and I originally get the following error: 

```
celery_1  | Traceback (most recent call last):
celery_1  |   File "/root/anaconda3/lib/python3.7/site-packages/billiard/pool.py", line 366, in workloop
celery_1  |     put((READY, (job, i, result, inqW_fd)))
celery_1  |   File "/root/anaconda3/lib/python3.7/site-packages/billiard/queues.py", line 366, in put
celery_1  |     self.send_payload(ForkingPickler.dumps(obj))
celery_1  |   File "/root/anaconda3/lib/python3.7/site-packages/billiard/reduction.py", line 56, in dumps
celery_1  |     cls(buf, protocol).dump(obj)
celery_1  | billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: ResourceExhaustedError()>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'tensorflow.python.framework.errors_impl.ResourceExhaustedError\'>: it\'s not the same object as tensorflow.python.framework.errors_impl.ResourceExhaustedError")''.
```

upon trying to rerun the celery worker I get the first error posted above. From reading this thread it is not clear to me whether this is an error related to celery or my work environment. 

Here is my `docker-compose.yml` file for reference: 

```
version: "2.3"

services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app
    container_name: my-app
    runtime: nvidia
    links:
      - redis
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    command: "python app.py"

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "celery -A worker.celery worker --loglevel=INFO"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    links:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:latest

```
with docker image 

```
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
```

**Comment by veerendrapolepalli** [comment]
It happening for me with billiyard only , i have tried running it from the command line with or with out using celery , 

 File "/venv7/lib/python3.7/site-packages/billiard/pool.py", line 1399, in starmap
    starmapstar, chunksize).get()
  File "/venv7/lib/python3.7/site-packages/billiard/pool.py", line 1791, in get
    raise self._value.exception
  File "/venv7/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).

i am using celery latest version 4.4.7 and billiard 3.6.3.0 and kombu 5.0.1 

When i was trying to run the multiprocessing pool job in celery it wasnt not allowing to run it , so i shifted billiard pool for parallel processing 

i was trying to run about from command line with 32 parallel jobs using billiard i got this error and if shift back to multiprocessing i am not getting this error.

Stuck with this problem in celery , please suggest me if i need to change any default settings

**Comment by roooooody** [comment]
I have same issue
`[2020-11-02 23:09:41,791: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0.')
Traceback (most recent call last):
  File "/usr/local/python38/lib/python3.8/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0.
`

in file /usr/local/python38/lib/python3.8/site-packages/billiard/pool.py , the function _join_exited_workers in line 1168 explain
`
Cleanup after any worker processes which have exited due to  reaching their specified lifetime. Returns True if any workers were  cleaned up.
`

Exit after exception use exit() in my function , so change mode exit, solve it 
I hope it will help you

**Comment by shintaii** [comment]
Hi,

I had same issue and fixed it... I never got any issues with Celery and suddenly alot. So what changed? I had turned AutoScale on... and the problems started. I disabled Autoscale and all issues are gone. No more WorkerLost Error. 

Hope it helps.

**Comment by imKKK** [comment]
> Hi,
> 
> I had same issue and fixed it... I never got any issues with Celery and suddenly alot. So what changed? I had turned AutoScale on... and the problems started. I disabled Autoscale and all issues are gone. No more WorkerLost Error.
> 
> Hope it helps.

Thanks a lot @shintaii , this worked for us.

**Comment by Bialomazur** [comment]
Any Updates on this?

I getting the exact same Error message  and am not using the autoscale-option.
Celery ver. 5.0.5

**Comment by Bialomazur** [comment]
Maybe it will help someone:

If your celery tasks are exiting "silently" without any particular traceback & the error message "worker lost error code 0", run your task outside of celery in a terminal and debug it. Often times when there's an exception, Celery does not throw it **even** when you put it inside of try & except. For me it was a sneaky **Recursion-depth-Exception** which Celery seemingly could not handle.

**Comment by jackton1** [comment]
Any updates on this still experiencing issues with celery `4.4.6`

**Comment by bangbao** [comment]
I had some error on celery 4.3.0, Any updates can fix it?

**Comment by cosmos-sajal** [comment]
Any updates? I am still stuck with this.

**Comment by sorenwacker** [comment]
I only get this message, no logs:

celery exited with code 0
celery exited with code 0
celery exited with code 0
celery exited with code 0
celery exited with code 0
celery exited with code 0
celery exited with code 0
celery exited with code 0

**Comment by parthokr** [comment]
Damn still on 5.2.7

**Comment by timmyomahony** [comment]
I was encountering this issue on Digital Ocean with Ubuntu and came to realise that it was a memory issue. My workers were being killed when the memory hit 100%, causing the errors. I reduced the worker count  and these errors disappeared (alternatively you could just bump-up RAM on your instance).

**Comment by balodja** [comment]
I had the same issue due to throwing wrong Exception object, i.e. inherited from `BaseException` instead of `Exception`. Simple example to reproduce:
```
@app.task
def odd_task():
    raise BaseException("touch me!")
```

Thus the output:
```
[2023-08-11 00:09:02,767: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0 Job: 0.')
Traceback (most recent call last):
  File "/nix/store/glzz5klj1bxh1kzwlkmlcq0y77z5pzql-python3-3.11.4-env/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/nix/store/glzz5klj1bxh1kzwlkmlcq0y77z5pzql-python3-3.11.4-env/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0 Job: 0.
```

**Comment by imsks** [comment]
> I don't know, but I installed eventlet and change celery loop via command line parameter '-P eventlet' and it work's now

This worked.

**Comment by TacoBel42** [comment]
Looks like the continue of this issue https://github.com/celery/celery/issues/3398
In my case, i have crash with requests_kerberos lib
