### ISSUE TITLE
FileNotFoundError with context.Value('i')

### ISSUE THREAD

**Issue by azmeuk** [celery/billiard#338]
Hi. I use Alpine 3.14 with python 3.9.5 and billiard 3.6.4 and celery 5.1.2 and the following code raises an exception I do not really understand.

The original issue is [this one](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C8876736ccfb1a1c3affcfa70d1a62e47a93041f9.camel%40aquilenet.fr%3E) in the sourcehut mailing list.

```python
>>> from billiard.pool import get_context
>>> ctx = get_context()
>>> ctx.Value('i')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/billiard/context.py", line 181, in Value
    return Value(typecode_or_type, *args, lock=lock,
  File "/usr/lib/python3.9/site-packages/billiard/sharedctypes.py", line 83, in Value
    lock = ctx.RLock()
  File "/usr/lib/python3.9/site-packages/billiard/context.py", line 110, in RLock
    return RLock(ctx=self.get_context())
  File "/usr/lib/python3.9/site-packages/billiard/synchronize.py", line 209, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
  File "/usr/lib/python3.9/site-packages/billiard/synchronize.py", line 72, in __init__
    sl = self._semlock = _billiard.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```
This happens with the system package, but also in a virtualenv.

After some digging, I could isolate that the error can be reproduced by:

```python
>>> import _multiprocessing
>>> _multiprocessing.SemLock(0, 1, 1, "/mp-xt439jcr", True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory
```

What file is actually not found? How can I solve this?

**Comment by azmeuk** [comment]
I suppose this was due to `/dev/shm` missing in my LXC alpine container. Running `sudo rc-update add devfs boot` then rebooting the container fixed the issue.
