### ISSUE TITLE
Worker exited prematurely: signal 9 (SIGKILL) Job: 10.

### ISSUE THREAD

**Issue by ArslanDevPy** [celery/billiard#380]
**celery==5.2.7
billiard==3.6.4.0**

[2022-11-08 10:22:12,972: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:19 exited with 'signal 9 (SIGKILL)'
[2022-11-08 10:22:13,375: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 10.')
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 10.

**Comment by MrMagicHD** [comment]
Same Error while consume (3 MB file with 200 dpi and 15 pages + many more files sometimes one pagers):

[2023-08-22 21:53:21,150: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:888 exited with 'signal 9 (SIGKILL)'
[2023-08-22 21:53:21 +0200] [171] [ERROR] Worker (pid:256) was sent SIGKILL! Perhaps out of memory?
[2023-08-22 21:53:21,203] [ERROR] [celery.worker.request] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 7.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
paperless-ngx-webserver-1   |billiard.einfo.ExceptionWithTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 7.
"""
2023-08-22 19:53:22,206 INFO reaped unknown pid 930 (terminated by SIGPIPE)
2023-08-22 19:53:22,206 INFO reaped unknown pid 929 (terminated by SIGPIPE)

Please help on that error, many documents get not consumed because of that error that is very bad.
