### ISSUE TITLE
TypeError when using `soft_timeout` or `timeout` on `Pool`

### ISSUE THREAD

**Issue by murrple-1** [celery/billiard#385]
When calling code like
```python
with Pool(job_data.n_cpu, timeout=5) as pool:
    results = pool.starmap(long_running_calculation, [...])
```
or
```python
with Pool(job_data.n_cpu, soft_timeout=5) as pool:
    results = pool.starmap(long_running_calculation, [...])
```
we are seeing errors like this:
```
Thread 'TimeoutHandler' crashed: TypeError('can only concatenate list (not "int") to list')
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/billiard/pool.py", line 503, in run
    return self.body()
           ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/billiard/pool.py", line 762, in body
    for _ in self.handle_timeouts():
  File "/venv/lib/python3.11/site-packages/billiard/pool.py", line 752, in handle_timeouts
    if _timed_out(ack_time, [soft|hard]_timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/billiard/pool.py", line 730, in _timed_out
    if monotonic() >= start + timeout:
                      ~~~~~~^~~~~~~~~
TypeError: can only concatenate list (not "int") to list`
```

Please advise?

**Comment by Nusnus** [comment]
> Iam having the same issue would be nice to get an anwser so this.

Do you want to contribute a fix?
I’ll help review it and release a new patch version afterward.
