### ISSUE TITLE
Process doesn't run target function after call to celery's app.control().inspect() 

### ISSUE THREAD

**Issue by CharlesB2** [celery/billiard#401]
Identified a conflict between calling celery's control inspector and running subprocess from billiard. After the call to inspector, process is started without running the target function.

Conditions to reproduce:

- Use celery with a Redis broker (no issue with RabbitMQ)
- celery 5.3.6, billiard 4.2.0
- Have a celery task that uses billiard's Process to start a function
- Call `app.control.inspect().active()`
- child process is started, but the target function doesn’t run, and calling parent.conn.recv() results in EOFError

Full reproduction code here https://github.com/CharlesB2/billiard_broken_process

```
❯ docker compose exec celery python /app/broken_billiard_repro.py
calling function
child: conn.closed=False, conn.fileno()=4, conn.readable=True, conn.writable=True
child_conn.closed=False, child_conn.fileno()=4, child_conn.readable=True, child_conn.writable=True
Result: 42
calling function as task
child: conn.closed=False, conn.fileno()=4, conn.readable=True, conn.writable=True
child_conn.closed=False, child_conn.fileno()=4, child_conn.readable=True, child_conn.writable=True
Result: 42
getting active tasks
calling function
child: conn.closed=False, conn.fileno()=11, conn.readable=True, conn.writable=True
child_conn.closed=False, child_conn.fileno()=11, child_conn.readable=True, child_conn.writable=True
Result: 42
calling function as task
child_conn.closed=False, child_conn.fileno()=11, child_conn.readable=True, child_conn.writable=True
process killed
Traceback (most recent call last):
  File "/app/broken_billiard_repro.py", line 46, in <module>
    subprocess_fun_task()
  File "/app/.venv/lib/python3.10/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
  File "/app/.venv/lib/python3.10/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
  File "/app/broken_billiard_repro.py", line 34, in subprocess_fun_task
    subprocess_fun()
  File "/app/broken_billiard_repro.py", line 28, in subprocess_fun
    print(f"Result: {parent_conn.recv()}")
  File "/app/.venv/lib/python3.10/site-packages/billiard/connection.py", line 275, in recv
    buf = self._recv_bytes()
  File "/app/.venv/lib/python3.10/site-packages/billiard/connection.py", line 453, in _recv_bytes
    buf = self._recv(4)
  File "/app/.venv/lib/python3.10/site-packages/billiard/connection.py", line 427, in _recv
    raise EOFError
EOFError
```

**Comment by CharlesB2** [comment]
Actually reproduced in native multiprocessing, so closing in favour of https://github.com/celery/celery/issues/8874

**Comment by auvipy** [comment]
we use billiard, not native multiprocessing latest version, yet. although we should upgrade it.
