### ISSUE TITLE
Semaphore Lock Files Not Being Deleted

### ISSUE THREAD

**Issue by brendon-codes** [celery/billiard#5]
We are on Billiard 2.7.3.9. Billiard is creating semaphore lock files, but they don't seem to always be clearing out. Every few weeks, this seems to use up our entire disk, then causing entire server to crash. Here is the the stack trace:

[2012-07-11 16:42:07,735: (celery.worker) ERROR] Unrecoverable error: OSError(28, 'No space left on device')
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/celery-2.6.0rc5-py2.6.egg/celery/worker/**init**.py", line 350, in start
    component.start()
  File "/usr/local/lib/python2.6/dist-packages/celery-2.6.0rc5-py2.6.egg/celery/concurrency/base.py", line 109, in start
    self.on_start()
  File "/usr/local/lib/python2.6/dist-packages/celery-2.6.0rc5-py2.6.egg/celery/concurrency/processes/**init**.py", line 84, in on_start
    **self.options)
  File "/usr/local/lib/python2.6/dist-packages/billiard-2.7.3.9-py2.6-linux-i686.egg/billiard/pool.py", line 760, in **init**
    self._setup_queues()
  File "/usr/local/lib/python2.6/dist-packages/billiard-2.7.3.9-py2.6-linux-i686.egg/billiard/pool.py", line 990, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/local/lib/python2.6/dist-packages/billiard-2.7.3.9-py2.6-linux-i686.egg/billiard/queues.py", line 340, in __init__
    self._rlock = Lock()
  File "/usr/local/lib/python2.6/dist-packages/billiard-2.7.3.9-py2.6-linux-i686.egg/billiard/synchronize.py", line 171, in __init__
    SemLock.**init**(self, SEMAPHORE, 1, 1)
  File "/usr/local/lib/python2.6/dist-packages/billiard-2.7.3.9-py2.6-linux-i686.egg/billiard/synchronize.py", line 85, in **init**
    kind, value, maxvalue, self._make_name(), unlink_immediately)
OSError: [Errno 28] No space left on device

**Comment by Fanduzi** [comment]
same issue , How did you solve it?

**Comment by Fanduzi** [comment]
> Hi @Fanduzi did you figure out a solution here?

Not yet, the current solution is to restart the computer periodically. . .

**Comment by auvipy** [comment]
as er history was closed by https://github.com/celery/billiard/commit/bb096154cae6eb37668d473b8a682599b2bf1de9

**Comment by hbradlow** [comment]
Got it. I am still seeing this error using a version after that was merged.
